# -*- coding: utf-8 -*-
# Generated by Django 2.2.7 on 2019-11-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    """Removes the default value from ``is_clean`` from ``SomeItem``."""

    dependencies = [
        ('main_app', '0003_auto_20191119_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='someitem',
            name='is_clean',
            field=models.BooleanField(),
        ),
    ]
