# Generated by Django 5.2.9 on 2026-01-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration for testing ManyToManyField with through_fields."""

    dependencies = [
        ('main_app', '0005_auto_20200329_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeGroup',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SomeMember',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SomeMembership',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('invite_reason', models.CharField(max_length=50)),
                (
                    'group',
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        to='main_app.somegroup',
                    ),
                ),
                (
                    'member',
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        to='main_app.somemember',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='somegroup',
            name='members',
            field=models.ManyToManyField(
                through='main_app.SomeMembership',
                through_fields=('group', 'member'),
                to='main_app.somemember',
            ),
        ),
    ]
